### ISSUE TITLE
different result sovled by newton and sd 

### ISSUE THREAD

**Issue by dbdxnuliba** [cshelton/pyminfunc#3]
@cshelton 
this is the example code by newton
```import sys
sys.path.insert(0,'..')
from pyminfunc import minFunc
import numpy as np

def myf(x):
     sinx1 = np.sin(x[1])
     cosx1 = np.cos(x[1])
     f = x[0]**2 * sinx1**2 + (x[1]-10)**2 + (x[0]-10)**2
     g = np.array([2*x[0] * sinx1**2 + 2*(x[0]-10),
                   x[0]**2 * 2*sinx1 * cosx1 + 2*(x[1]-10)])
     h = np.array([[2*sinx1**2 +2, 2* x[0] * np.sin(2*x[1])], [2* x[0] * np.sin(2*x[1]), 2*(x[0])**2 * np.cos(2*x[1])]]) 
     return f,g,h

x0 = np.array([0,0])
options = {'display':'off','method':'newton'} # many more options possible
xmin,fmin,exitflag = minFunc(myf,x0,options)
print(xmin)
print(fmin)
```
and the result got by newton method is
xmin:[2.17466092e-07 9.99993042e+00]
fmin:99.99999565551938

2) when solve the same proble  sd method
```
import sys
sys.path.insert(0,'..')
from pyminfunc import minFunc
import numpy as np

def myf(x):
     sinx1 = np.sin(x[1])
     cosx1 = np.cos(x[1])
     f = x[0]**2 * sinx1**2 + (x[1]-10)**2 + (x[0]-10)**2
     g = np.array([2*x[0] * sinx1**2 + 2*(x[0]-10),
                   x[0]**2 * 2*sinx1 * cosx1 + 2*(x[1]-10)])
     return f,g

x0 = np.array([0,0])
options = {'display':'off','method':'sd'} # many more options possible
xmin,fmin,exitflag = minFunc(myf,x0,options)
print(xmin)
print(fmin)
```
the result is:
xmin:[9.95300244 3.21034839]
fmin:46.5691423690171

Question:
could you please tell me why the result is not same and **is anywhere  gradient or hessain in myf function**  is wrong

**Comment by cshelton** [comment]
Different algorithms may give different results in general, as they each seek a *local* minimum.  

As I mentioned in #2, I think the gradient in my example.py is incorrect (I think the version in #2 is correct), so that could also account for the problem.  I think your Hessian is incorrect (sinx1**2 is sin(x1)*sin(x1) and not sin(x1*x1)).  But, I am not near my normal development environment currently and cannot check currently.

In general, this codebase's development was halted before all algorithms could be fully tested.

**Comment by dbdxnuliba** [comment]
thanks
