### ISSUE TITLE
I  found  wrong result cause by  Adjusting Hessianin minFunc.py

### ISSUE THREAD

**Issue by dbdxnuliba** [cshelton/pyminfunc#4]
@cshelton By run a demo RosenBrock Banana Function 
![image](https://user-images.githubusercontent.com/13350158/232358639-f391c28e-a613-4fb1-b8cb-370f3b75dd51.png)
the true xmin is xmin = [1,1]
and the test demo here is:
```
import sys
sys.path.insert(0,'..')
from pyminfunc import minFunc
import numpy as np

def myf(x):
     sinx1 = np.sin(x[1])
     cosx1 = np.cos(x[1])
     f= 100*(x[0]**2-x[1])** 2+(x[0]-1)**2  
     g = np.array([400*x[0]*(x[0]**2-x[1])+2*(x[0]-1), -200*(x[0]**2-x[1])])     
     h11 = 400*(x[0]**2-x[1]) + 400 *x[0] * 2*x[0] +2
     h12 = -400 *  x[0]
     h21 = h12
     h22 = 200
     h = np.array([[h11,h12], [h21,h22]]) 
     return f,g,h

x0 = np.array([-0.5,2.0])
#options = {'display':'off'} # many more options possible
options = {'display':'off','method':'newton'} # many more options possible
xmin,fmin,exitflag = minFunc(myf,x0,options)
print(xmin)
print(fmin)
```
I  found  wrong result it print in terminal is:
![image](https://user-images.githubusercontent.com/13350158/232358174-662576b4-448b-4f28-b631-76d2ae230962.png)
and xmin =[-0.5  2.] ,so we got wrong result
and I have found the related code about your modify hessian in  minFunc.py
 **H = H + np.eye(g.shape[0])*max(0,1e-12 - np.min(np.real(la.eigh(H)[0])))** 

and then I modify the related code about modify hessian
    omega = min(1e-2,1e-2 * norm(g)/(np.abs(H).max()))
    H = H + np.eye(g.shape[0])*omega

and run the demo  again can get another result :
![image](https://user-images.githubusercontent.com/13350158/232358424-cf9233c2-bccf-4e77-a869-1da6c3f0f826.png)
xmin =[0.99999931 0.99999859] ,we can got the right result now,

Quesiton:
1)can you tell me the refered materials about this formula  **H = H + np.eye(g.shape[0])*max(0,1e-12 - np.min(np.real(la.eigh(H)[0])))** in minFunc.py you use ,
2) how can we imporve the robustness of the modified hessian

**Comment by dbdxnuliba** [comment]
could you please look at the issue @cshelton

**Comment by cshelton** [comment]
I am traveling currently, so my responses may be slow.

Hessian methods can converge to local maxima.  You should read on Newton methods generally to understand how they work and why.  This happens when the Hessian is not positive-definite.  Adding some of the identity matrix can (if the amount is large enough) change the Hessian to be positive-definite.  General Newton (or Newton-Raphson) methods check for "uphill steps" and reverse to CG or other first-order methods when this happens.

This is a (more-or-less) direct translation of Mark Schmidt's Matlab optimization function(s).  The goal is to produce (as near as possible) exactly the same result as his library, so that algorithms written in Matlab can be ported to python.  To that end, I don't want to "fix" behavior that duplicates Mark's library's behavior.  However, if Mark's library does something different in this case, then I can try to take a look to see why this python rewriting isn't mirroring his library's behavior.

**Comment by dbdxnuliba** [comment]
ok ,thanks a lot 
and could you please give the web link codeabout the Mark Schmidt's Matlab optimization function(s) about modified newton method about here
 this formula *H = H + np.eye(g.shape[0])max(0,1e-12 - np.min(np.real(la.eigh(H)[0]))) in minFunc.py you use ,

**Comment by cshelton** [comment]
Mark's code is available from the link listed on the README: https://www.cs.ubc.ca/~schmidtm/Software/minFunc.html

The formula listed basically subtracts I times the smallest (which is negative) eigenvalue from H.  This will cause all eigenvalues to be non-negative.  A quick web search for Newton's method and identity matrix and eigenvalues will give a number of references to different ways of stabilizing Newton's method.  I'm not prepared to give an in-depth tutorial on optimization; that is a large topic and there are many good books and other references available, especially for an algorithm as common as Newton's method.

**Comment by dbdxnuliba** [comment]
thanks a lot
